Use os.remove instead of shutil.remove. It exists.
This fixes the following error that would occur when attempting to
remove the ZenPack.

    AttributeError: 'module' object has no attribute 'remove'